name: "Publish Package on pub.dev"

on:
  push:
    branches:
      - master

jobs:
  publish:
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: "2.5.1"
    - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
