name: "Publish Package on pub.dev"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Package on pub.dev
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v1

      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.6
